'use client'
import { useState } from 'react'
import { generateNotes, generateFlashcards, answerQuestion } from '@/lib/gemini'
import { useSubStore, useUIStore } from '@/lib/store'
import type { Flashcard } from '@/lib/supabase'

function MarkdownOutput({ text }: { text: string }) {
  const html = text
    .replace(/## (.*)/g, '<h2>$1</h2>')
    .replace(/### (.*)/g, '<h3>$1</h3>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^- (.*)/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>)/gs, '<ul>$1</ul>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(?!<[hul])/gm, '')
  return <div className="md-content" dangerouslySetInnerHTML={{ __html: `<p>${html}</p>` }} />
}

export function AIPage() {
  const { canUseAI, incrementAIUsage, plan } = useSubStore()
  const { setActivePage } = useUIStore()

  const [notesText, setNotesText]       = useState('')
  const [notesLoading, setNotesLoading] = useState(false)
  const [cards, setCards]               = useState<Flashcard[]>([])
  const [cardIdx, setCardIdx]           = useState(0)
  const [flipped, setFlipped]           = useState(false)
  const [cardsLoading, setCardsLoading] = useState(false)
  const [question, setQuestion]         = useState('')
  const [answer, setAnswer]             = useState('')
  const [ansLoading, setAnsLoading]     = useState(false)
  const [topic, setTopic]               = useState('Engineering Mathematics II — Differential Equations')

  async function handleNotes() {
    if (!canUseAI()) { setActivePage('pricing'); return }
    setNotesLoading(true); incrementAIUsage()
    try { setNotesText(await generateNotes(topic)) }
    catch (e: any) { setNotesText(`Error: ${e.message}`) }
    setNotesLoading(false)
  }

  async function handleFlashcards() {
    if (!canUseAI()) { setActivePage('pricing'); return }
    setCardsLoading(true); incrementAIUsage()
    try {
      const fc = await generateFlashcards(topic)
      setCards(fc); setCardIdx(0); setFlipped(false)
    } catch {}
    setCardsLoading(false)
  }

  async function handleAsk() {
    if (!question.trim()) return
    if (!canUseAI()) { setActivePage('pricing'); return }
    setAnsLoading(true); incrementAIUsage()
    try { setAnswer(await answerQuestion(question, topic)) }
    catch (e: any) { setAnswer(`Error: ${e.message}`) }
    setAnsLoading(false)
  }

  return (
    <div>
      {plan === 'free' && (
        <div className="msg msg-info" style={{ marginBottom: 20, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <span>Free plan: 5 AI generations/month. <strong>Upgrade for unlimited access.</strong></span>
          <button className="btn btn-primary" style={{ padding: '6px 14px', fontSize: 12 }} onClick={() => setActivePage('pricing')}>Upgrade</button>
        </div>
      )}

      {/* Topic input */}
      <div className="card" style={{ marginBottom: 20 }}>
        <label className="form-label">Topic / Course Title</label>
        <input className="form-input" value={topic} onChange={e => setTopic(e.target.value)}
          placeholder="e.g. Organic Chemistry — Alkenes" />
      </div>

      {/* Action cards */}
      <div className="grid2" style={{ marginBottom: 20 }}>
        <div className="ai-card" style={{ cursor: 'pointer' }} onClick={handleNotes}>
          <div className="ai-glow" />
          <div style={{ fontSize: 24, marginBottom: 8 }}>📝</div>
          <div style={{ fontSize: 15, fontWeight: 600, marginBottom: 4 }}>Auto-Generate Notes</div>
          <div style={{ fontSize: 12, color: 'var(--text2)' }}>Structured study notes via Gemini AI</div>
        </div>
        <div className="ai-card" style={{ cursor: 'pointer' }} onClick={handleFlashcards}>
          <div className="ai-glow" />
          <div style={{ fontSize: 24, marginBottom: 8 }}>🃏</div>
          <div style={{ fontSize: 15, fontWeight: 600, marginBottom: 4 }}>Flashcard Generator</div>
          <div style={{ fontSize: 12, color: 'var(--text2)' }}>8 study flashcards generated by Gemini AI</div>
        </div>
      </div>

      {/* Notes output */}
      {(notesLoading || notesText) && (
        <div className="card" style={{ marginBottom: 20 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 }}>
            <span style={{ fontSize: 18 }}>✨</span>
            <span style={{ fontSize: 15, fontWeight: 600 }}>AI-Generated Notes</span>
            <span className="badge badge-green">Gemini</span>
          </div>
          {notesLoading
            ? <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--purple)', fontSize: 13 }}><div className="dot-pulse"><span/><span/><span/></div> Generating with Gemini AI…</div>
            : <MarkdownOutput text={notesText} />
          }
        </div>
      )}

      {/* Flashcards output */}
      {(cardsLoading || cards.length > 0) && (
        <div style={{ marginBottom: 20 }}>
          <div className="section-head">
            <div className="section-title">🃏 AI Flashcards ({cards.length})</div>
            <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
              <button className="btn btn-ghost" onClick={() => { setCardIdx(i => (i - 1 + cards.length) % cards.length); setFlipped(false) }}>← Prev</button>
              <span style={{ fontSize: 13, color: 'var(--text3)' }}>{cardIdx + 1} / {cards.length}</span>
              <button className="btn btn-ghost" onClick={() => { setCardIdx(i => (i + 1) % cards.length); setFlipped(false) }}>Next →</button>
            </div>
          </div>
          {cardsLoading
            ? <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--purple)', fontSize: 13 }}><div className="dot-pulse"><span/><span/><span/></div> Generating flashcards…</div>
            : (
              <div>
                <div className={`flashcard${flipped ? ' flipped' : ''}`} onClick={() => setFlipped(f => !f)}>
                  <div className="flashcard-inner">
                    <div className="flashcard-front">{cards[cardIdx]?.q}</div>
                    <div className="flashcard-back">{cards[cardIdx]?.a}</div>
                  </div>
                </div>
                <div style={{ fontSize: 12, color: 'var(--text3)', textAlign: 'center', marginTop: 8 }}>Click card to flip</div>
              </div>
            )
          }
        </div>
      )}

      {/* Ask AI */}
      <div className="card">
        <div className="section-title" style={{ marginBottom: 16 }}>💬 Ask Gemini AI</div>
        <div style={{ display: 'flex', gap: 10 }}>
          <input className="form-input" style={{ flex: 1 }} value={question}
            onChange={e => setQuestion(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && handleAsk()}
            placeholder="e.g. Explain Laplace transforms in simple terms…" />
          <button className="btn btn-primary" onClick={handleAsk} disabled={ansLoading}>
            {ansLoading ? '…' : 'Ask →'}
          </button>
        </div>
        {ansLoading && (
          <div style={{ marginTop: 14, display: 'flex', alignItems: 'center', gap: 8, color: 'var(--purple)', fontSize: 13 }}>
            <div className="dot-pulse"><span/><span/><span/></div> Gemini is thinking…
          </div>
        )}
        {answer && !ansLoading && (
          <div style={{ marginTop: 14, padding: 14, background: 'var(--bg3)', borderRadius: 8 }}>
            <div style={{ fontSize: 12, color: 'var(--purple)', fontWeight: 600, marginBottom: 8 }}>🤖 Gemini AI:</div>
            <MarkdownOutput text={answer} />
          </div>
        )}
      </div>
    </div>
  )
}
export default AIPage